# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 909bacc6a1851c6835600d8f7e64a701d6e9dc3f36e54eb9d1ac4eb57da515b3b70cf784548f560437d78d3d1e5fe3b4e65765a5e0a8e25e8ae2aac12588278c

test:
  secret_key_base: 6a39257cf41303cd384034bbd6dea8598db9e91c8325d63626b323e6d89921058cc21ccd9c384f09aa785e3c664ea9ad8f3af6d5d6e676a11647762235b78229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
